;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="Damage.Default",NewTagName="Damage.Directional")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Attack",DevComment="")
+GameplayTagList=(Tag="Ability.Block",DevComment="")
+GameplayTagList=(Tag="Ability.Dead",DevComment="")
+GameplayTagList=(Tag="Ability.Dodge",DevComment="")
+GameplayTagList=(Tag="Ability.Equip",DevComment="")
+GameplayTagList=(Tag="Ability.Interact",DevComment="")
+GameplayTagList=(Tag="Ability.Jump",DevComment="")
+GameplayTagList=(Tag="Ability.Lock",DevComment="")
+GameplayTagList=(Tag="Ability.Vampire",DevComment="")
+GameplayTagList=(Tag="Character.Enemy",DevComment="")
+GameplayTagList=(Tag="Character.Player",DevComment="")
+GameplayTagList=(Tag="Character.Possessed",DevComment="")
+GameplayTagList=(Tag="Damage.Crasher",DevComment="")
+GameplayTagList=(Tag="Damage.Default.FromBack",DevComment="")
+GameplayTagList=(Tag="Damage.Default.FromFront",DevComment="")
+GameplayTagList=(Tag="Damage.Default.FromLeft",DevComment="")
+GameplayTagList=(Tag="Damage.Default.FromRight",DevComment="")
+GameplayTagList=(Tag="Damage.Directional",DevComment="")
+GameplayTagList=(Tag="Damage.Environmental.Sun",DevComment="")
+GameplayTagList=(Tag="Damage.FromAir",DevComment="")
+GameplayTagList=(Tag="Damage.Impact",DevComment="")
+GameplayTagList=(Tag="Damage.Launch",DevComment="")
+GameplayTagList=(Tag="Damage.Puncture",DevComment="")
+GameplayTagList=(Tag="Damage.Slash",DevComment="")
+GameplayTagList=(Tag="Damage.Upper",DevComment="")
+GameplayTagList=(Tag="Data.Attributes.Energy",DevComment="")
+GameplayTagList=(Tag="Data.Damage.Sun",DevComment="")
+GameplayTagList=(Tag="Death.Default",DevComment="")
+GameplayTagList=(Tag="Effect.Camera.Shake.Rock",DevComment="")
+GameplayTagList=(Tag="Effect.Camera.Zoom.HeavyHit",DevComment="")
+GameplayTagList=(Tag="Event.Damage.Sun",DevComment="")
+GameplayTagList=(Tag="Event.Damage.Sun.Activate",DevComment="")
+GameplayTagList=(Tag="Event.Damage.Sun.Deactivate",DevComment="")
+GameplayTagList=(Tag="Event.Death",DevComment="")
+GameplayTagList=(Tag="Event.Hit",DevComment="")
+GameplayTagList=(Tag="Event.Launch",DevComment="")
+GameplayTagList=(Tag="Event.Posses",DevComment="")
+GameplayTagList=(Tag="Event.Posses.Return",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.Default",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.Environmental.Sun",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.Impact",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.Puncture",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Event.Lever",DevComment="")
+GameplayTagList=(Tag="Holster.Melee.GreatSword",DevComment="")
+GameplayTagList=(Tag="Holster.Melee.Sword",DevComment="")
+GameplayTagList=(Tag="SavedData.Attributes.Energy",DevComment="")
+GameplayTagList=(Tag="SavedData.Attributes.Health",DevComment="")
+GameplayTagList=(Tag="SavedData.Attributes.Shield",DevComment="")
+GameplayTagList=(Tag="State.Attacking",DevComment="")
+GameplayTagList=(Tag="State.Busy",DevComment="")
+GameplayTagList=(Tag="State.ComboWindow",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="State.Dodging",DevComment="")
+GameplayTagList=(Tag="State.Locking",DevComment="")
+GameplayTagList=(Tag="Weapon.Melee.GreatSword",DevComment="")
+GameplayTagList=(Tag="Weapon.Melee.Sword",DevComment="")

