;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Attack",DevComment="")
+GameplayTagList=(Tag="Ability.Block",DevComment="")
+GameplayTagList=(Tag="Ability.Dead",DevComment="")
+GameplayTagList=(Tag="Ability.Dodge",DevComment="")
+GameplayTagList=(Tag="Ability.Jump",DevComment="")
+GameplayTagList=(Tag="Ability.Launch",DevComment="")
+GameplayTagList=(Tag="Ability.Lock",DevComment="")
+GameplayTagList=(Tag="Damage.Crasher",DevComment="")
+GameplayTagList=(Tag="Damage.Default",DevComment="")
+GameplayTagList=(Tag="Damage.Default.FromBack",DevComment="")
+GameplayTagList=(Tag="Damage.Default.FromFront",DevComment="")
+GameplayTagList=(Tag="Damage.Default.FromLeft",DevComment="")
+GameplayTagList=(Tag="Damage.Default.FromRight",DevComment="")
+GameplayTagList=(Tag="Damage.FromAir",DevComment="")
+GameplayTagList=(Tag="Damage.Impact",DevComment="")
+GameplayTagList=(Tag="Damage.Launch",DevComment="")
+GameplayTagList=(Tag="Damage.Puncture",DevComment="")
+GameplayTagList=(Tag="Damage.Slash",DevComment="")
+GameplayTagList=(Tag="Damage.Upper",DevComment="")
+GameplayTagList=(Tag="Death.Default",DevComment="")
+GameplayTagList=(Tag="Event.Hit",DevComment="")
+GameplayTagList=(Tag="Event.Launch",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.Default",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.Impact",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.Puncture",DevComment="")
+GameplayTagList=(Tag="Holster.Melee.GreatSword",DevComment="")
+GameplayTagList=(Tag="Holster.Melee.Sword",DevComment="")
+GameplayTagList=(Tag="State.Airborne",DevComment="")
+GameplayTagList=(Tag="State.Launching",DevComment="")
+GameplayTagList=(Tag="State.Locking",DevComment="")
+GameplayTagList=(Tag="Weapon.Melee.GreatSword",DevComment="")
+GameplayTagList=(Tag="Weapon.Melee.Sword",DevComment="")
+GameplayTagList=(Tag="Weapon.Ranged.Pistol",DevComment="")

